languageCode = "en-us"
title = "Omkar's Blog"
theme = "hugo-ink"
paginate = 5

# copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "Thoughts and experiences"

	# Optional 64x64 avatar image.
	avatar = "omkar.png"

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Resume"
icon = "filt-text"
url = "https://drive.google.com/file/d/1ov0IreMlfzWN4bvXHpDRj533g8uukt0i/view"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://x.com/omkartenkale"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/omkar-tenkale"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/omkartenkale"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/omkartenkale"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://www.youtube.com/channel/UCCXe8bKHwqQspPI7qAzTA5w"

[taxonomies]
   tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
